export const initColors = [
  {color: "Absolute Zero", uniqueId: 1},
  {color: "Acid green", uniqueId: 2},
  {color: "Aero", uniqueId: 3},
  {color: "Aero blue", uniqueId: 4},
  {color: "African violet", uniqueId: 5},
  {color: "Air superiority blue", uniqueId: 6},
  {color: "Alabaster", uniqueId: 7},
  {color: "Alice blue", uniqueId: 8},
  {color: "Alloy orange", uniqueId: 9},
  {color: "Almond", uniqueId: 10},
  {color: "Amaranth", uniqueId: 11},
  {color: "Amaranth (M&P)", uniqueId: 12},
  {color: "Amaranth pink", uniqueId: 13},
  {color: "Amaranth purple", uniqueId: 14},
  {color: "Amaranth red", uniqueId: 15},
  {color: "Amazon", uniqueId: 16},
  {color: "Amber", uniqueId: 17},
  {color: "Amber (SAE/ECE)", uniqueId: 18},
  {color: "Amethyst", uniqueId: 19},
  {color: "Android green", uniqueId: 20},
  {color: "Antique brass", uniqueId: 21},
  {color: "Antique bronze", uniqueId: 22},
  {color: "Antique fuchsia", uniqueId: 23},
  {color: "Antique ruby", uniqueId: 24},
  {color: "Antique white", uniqueId: 25},
  {color: "Ao (English)", uniqueId: 26},
  {color: "Apple green", uniqueId: 27},
  {color: "Apricot", uniqueId: 28},
  {color: "Aqua", uniqueId: 29},
  {color: "Aquamarine", uniqueId: 30},
  {color: "Arctic lime", uniqueId: 31},
  {color: "Army green", uniqueId: 32},
  {color: "Artichoke", uniqueId: 33},
  {color: "Arylide yellow", uniqueId: 34},
  {color: "Ash gray", uniqueId: 35},
  {color: "Asparagus", uniqueId: 36},
  {color: "Atomic tangerine", uniqueId: 37},
  {color: "Auburn", uniqueId: 38},
  {color: "Aureolin", uniqueId: 39},
  {color: "Avocado", uniqueId: 40},
  {color: "Azure", uniqueId: 41},
  {color: "Azure (X11/web color)", uniqueId: 42},
  {color: "Baby blue", uniqueId: 43},
  {color: "Baby blue eyes", uniqueId: 44},
  {color: "Baby pink", uniqueId: 45},
  {color: "Baby powder", uniqueId: 46},
  {color: "Baker-Miller pink", uniqueId: 47},
  {color: "Banana Mania", uniqueId: 48},
  {color: "Barbie Pink", uniqueId: 49},
  {color: "Barn red", uniqueId: 50},
  {color: "Battleship grey", uniqueId: 51},
  {color: "Beau blue", uniqueId: 52},
  {color: "Beaver", uniqueId: 53},
  {color: "Beige", uniqueId: 54},
  {color: "B'dazzled blue", uniqueId: 55},
  {color: "Big dip o’ruby", uniqueId: 56},
  {color: "Bisque", uniqueId: 57},
  {color: "Bistre", uniqueId: 58},
  {color: "Bistre brown", uniqueId: 59},
  {color: "Bitter lemon", uniqueId: 60},
  {color: "Bitter lime", uniqueId: 61},
  {color: "Bittersweet", uniqueId: 62},
  {color: "Bittersweet shimmer", uniqueId: 63},
  {color: "Black", uniqueId: 64},
  {color: "Black bean", uniqueId: 65},
  {color: "Black chocolate", uniqueId: 66},
  {color: "Black coffee", uniqueId: 67},
  {color: "Black coral", uniqueId: 68},
  {color: "Black olive", uniqueId: 69},
  {color: "Black Shadows", uniqueId: 70},
  {color: "Blanched almond", uniqueId: 71},
  {color: "Blast-off bronze", uniqueId: 72},
  {color: "Bleu de France", uniqueId: 73},
  {color: "Blizzard blue", uniqueId: 74},
  {color: "Blond", uniqueId: 75},
  {color: "Blood red", uniqueId: 76},
  {color: "Blue", uniqueId: 77},
  {color: "Blue (Crayola)", uniqueId: 78},
  {color: "Blue (Munsell)", uniqueId: 79},
  {color: "Blue (NCS)", uniqueId: 80},
  {color: "Blue (Pantone)", uniqueId: 81},
  {color: "Blue (pigment)", uniqueId: 82},
  {color: "Blue (RYB)", uniqueId: 83},
  {color: "Blue bell", uniqueId: 84},
  {color: "Blue-gray", uniqueId: 85},
  {color: "Blue-green", uniqueId: 86},
  {color: "Blue-green (color wheel)", uniqueId: 87},
  {color: "Blue jeans", uniqueId: 88},
  {color: "Blue sapphire", uniqueId: 89},
  {color: "Blue-violet", uniqueId: 90},
  {color: "Blue-violet (Crayola)", uniqueId: 91},
  {color: "Blue-violet (color wheel)", uniqueId: 92},
  {color: "Blue yonder", uniqueId: 93},
  {color: "Bluetiful", uniqueId: 94},
  {color: "Blush", uniqueId: 95},
  {color: "Bole", uniqueId: 96},
  {color: "Bone", uniqueId: 97},
  {color: "Bottle green", uniqueId: 98},
  {color: "Brandy", uniqueId: 99},
  {color: "Brick red", uniqueId: 100},
  {color: "Bright green", uniqueId: 101},
  {color: "Bright lilac", uniqueId: 102},
  {color: "Bright maroon", uniqueId: 103},
  {color: "Bright navy blue", uniqueId: 104},
  {color: "Bright yellow (Crayola)", uniqueId: 105},
  {color: "Brilliant rose", uniqueId: 106},
  {color: "Brink pink", uniqueId: 107},
  {color: "British racing green", uniqueId: 108},
  {color: "Bronze", uniqueId: 109},
  {color: "Brown", uniqueId: 110},
  {color: "Brown sugar", uniqueId: 111},
  {color: "Brunswick green", uniqueId: 112},
  {color: "Bud green", uniqueId: 113},
  {color: "Buff", uniqueId: 114},
  {color: "Burgundy", uniqueId: 115},
  {color: "Burlywood", uniqueId: 116},
  {color: "Burnished brown", uniqueId: 117},
  {color: "Burnt orange", uniqueId: 118},
  {color: "Burnt sienna", uniqueId: 119},
  {color: "Burnt umber", uniqueId: 120},
  {color: "Byzantine", uniqueId: 121},
  {color: "Byzantium", uniqueId: 122},
  {color: "Cadet", uniqueId: 123},
  {color: "Cadet blue", uniqueId: 124},
  {color: "Cadet blue (Crayola)", uniqueId: 125},
  {color: "Cadet grey", uniqueId: 126},
  {color: "Cadmium green", uniqueId: 127},
  {color: "Cadmium orange", uniqueId: 128},
  {color: "Cadmium red", uniqueId: 129},
  {color: "Cadmium yellow", uniqueId: 130},
  {color: "Café au lait", uniqueId: 131},
  {color: "Café noir", uniqueId: 132},
  {color: "Cambridge blue", uniqueId: 133},
  {color: "Camel", uniqueId: 134},
  {color: "Cameo pink", uniqueId: 135},
  {color: "Canary", uniqueId: 136},
  {color: "Canary yellow", uniqueId: 137},
  {color: "Candy apple red", uniqueId: 138},
  {color: "Candy pink", uniqueId: 139},
  {color: "Capri", uniqueId: 140},
  {color: "Caput mortuum", uniqueId: 141},
  {color: "Cardinal", uniqueId: 142},
  {color: "Caribbean green", uniqueId: 143},
  {color: "Carmine", uniqueId: 144},
  {color: "Carmine (M&P)", uniqueId: 145},
  {color: "Carnation pink", uniqueId: 146},
  {color: "Carnelian", uniqueId: 147},
  {color: "Carolina blue", uniqueId: 148},
  {color: "Carrot orange", uniqueId: 149},
  {color: "Castleton green", uniqueId: 150},
  {color: "Catawba", uniqueId: 151},
  {color: "Cedar Chest", uniqueId: 152},
  {color: "Celadon", uniqueId: 153},
  {color: "Celadon blue", uniqueId: 154},
  {color: "Celadon green", uniqueId: 155},
  {color: "Celeste", uniqueId: 156},
  {color: "Celtic blue", uniqueId: 157},
  {color: "Cerise", uniqueId: 158},
  {color: "Cerulean", uniqueId: 159},
  {color: "Cerulean blue", uniqueId: 160},
  {color: "Cerulean frost", uniqueId: 161},
  {color: "Cerulean (Crayola)", uniqueId: 162},
  {color: "CG blue", uniqueId: 163},
  {color: "CG red", uniqueId: 164},
  {color: "Champagne", uniqueId: 165},
  {color: "Champagne pink", uniqueId: 166},
  {color: "Charcoal", uniqueId: 167},
  {color: "Charleston green", uniqueId: 168},
  {color: "Charm pink", uniqueId: 169},
  {color: "Chartreuse (traditional)", uniqueId: 170},
  {color: "Chartreuse (web)", uniqueId: 171},
  {color: "Cherry blossom pink", uniqueId: 172},
  {color: "Chestnut", uniqueId: 173},
  {color: "Chili red", uniqueId: 174},
  {color: "China pink", uniqueId: 175},
  {color: "China rose", uniqueId: 176},
  {color: "Chinese red", uniqueId: 177},
  {color: "Chinese violet", uniqueId: 178},
  {color: "Chinese yellow", uniqueId: 179},
  {color: "Chocolate (traditional)", uniqueId: 180},
  {color: "Chocolate (web)", uniqueId: 181},
  {color: "Chocolate Cosmos", uniqueId: 182},
  {color: "Chrome yellow", uniqueId: 183},
  {color: "Cinereous", uniqueId: 184},
  {color: "Cinnabar", uniqueId: 185},
  {color: "Cinnamon Satin", uniqueId: 186},
  {color: "Citrine", uniqueId: 187},
  {color: "Citron", uniqueId: 188},
  {color: "Claret", uniqueId: 189},
  {color: "Cobalt blue", uniqueId: 190},
  {color: "Cocoa brown", uniqueId: 191},
  {color: "Coffee", uniqueId: 192},
  {color: "Columbia Blue", uniqueId: 193},
  {color: "Congo pink", uniqueId: 194},
  {color: "Cool grey", uniqueId: 195},
  {color: "Copper", uniqueId: 196},
  {color: "Copper (Crayola)", uniqueId: 197},
  {color: "Copper penny", uniqueId: 198},
  {color: "Copper red", uniqueId: 199},
  {color: "Copper rose", uniqueId: 200},
  {color: "Coquelicot", uniqueId: 201},
  {color: "Coral", uniqueId: 202},
  {color: "Coral pink", uniqueId: 203},
  {color: "Cordovan", uniqueId: 204},
  {color: "Corn", uniqueId: 205},
  {color: "Cornell red", uniqueId: 206},
  {color: "Cornflower blue", uniqueId: 207},
  {color: "Cornsilk", uniqueId: 208},
  {color: "Cosmic cobalt", uniqueId: 209},
  {color: "Cosmic latte", uniqueId: 210},
  {color: "Coyote brown", uniqueId: 211},
  {color: "Cotton candy", uniqueId: 212},
  {color: "Cream", uniqueId: 213},
  {color: "Crimson", uniqueId: 214},
  {color: "Crimson (UA)", uniqueId: 215},
  {color: "Crystal", uniqueId: 216},
  {color: "Cultured", uniqueId: 217},
  {color: "Cyan", uniqueId: 218},
  {color: "Cyan (process)", uniqueId: 219},
  {color: "Cyber grape", uniqueId: 220},
  {color: "Cyber yellow", uniqueId: 221},
  {color: "Cyclamen", uniqueId: 222},
  {color: "Dark blue-gray", uniqueId: 223},
  {color: "Dark brown", uniqueId: 224},
  {color: "Dark byzantium", uniqueId: 225},
  {color: "Dark cornflower blue", uniqueId: 226},
  {color: "Dark cyan", uniqueId: 227},
  {color: "Dark electric blue", uniqueId: 228},
  {color: "Dark goldenrod", uniqueId: 229},
  {color: "Dark green", uniqueId: 230},
  {color: "Dark green (X11)", uniqueId: 231},
  {color: "Dark jungle green", uniqueId: 232},
  {color: "Dark khaki", uniqueId: 233},
  {color: "Dark lava", uniqueId: 234},
  {color: "Dark liver", uniqueId: 235},
  {color: "Dark liver (horses)", uniqueId: 236},
  {color: "Dark magenta", uniqueId: 237},
  {color: "Dark moss green", uniqueId: 238},
  {color: "Dark olive green", uniqueId: 239},
  {color: "Dark orange", uniqueId: 240},
  {color: "Dark orchid", uniqueId: 241},
  {color: "Dark pastel green", uniqueId: 242},
  {color: "Dark purple", uniqueId: 243},
  {color: "Dark red", uniqueId: 244},
  {color: "Dark salmon", uniqueId: 245},
  {color: "Dark sea green", uniqueId: 246},
  {color: "Dark sienna", uniqueId: 247},
  {color: "Dark sky blue", uniqueId: 248},
  {color: "Dark slate blue", uniqueId: 249},
  {color: "Dark slate gray", uniqueId: 250},
  {color: "Dark spring green", uniqueId: 251},
  {color: "Dark turquoise", uniqueId: 252},
  {color: "Dark violet", uniqueId: 253},
  {color: "Dartmouth green", uniqueId: 254},
  {color: "Davy's grey", uniqueId: 255},
  {color: "Deep cerise", uniqueId: 256},
  {color: "Deep champagne", uniqueId: 257},
  {color: "Deep chestnut", uniqueId: 258},
  {color: "Deep jungle green", uniqueId: 259},
  {color: "Deep pink", uniqueId: 260},
  {color: "Deep saffron", uniqueId: 261},
  {color: "Deep sky blue", uniqueId: 262},
  {color: "Deep Space Sparkle", uniqueId: 263},
  {color: "Deep taupe", uniqueId: 264},
  {color: "Denim", uniqueId: 265},
  {color: "Denim blue", uniqueId: 266},
  {color: "Desert", uniqueId: 267},
  {color: "Desert sand", uniqueId: 268},
  {color: "Dim gray", uniqueId: 269},
  {color: "Dodger blue", uniqueId: 270},
  {color: "Dogwood rose", uniqueId: 271},
  {color: "Drab", uniqueId: 272},
  {color: "Duke blue", uniqueId: 273},
  {color: "Dutch white", uniqueId: 274},
  {color: "Earth yellow", uniqueId: 275},
  {color: "Ebony", uniqueId: 276},
  {color: "Ecru", uniqueId: 277},
  {color: "Eerie black", uniqueId: 278},
  {color: "Eggplant", uniqueId: 279},
  {color: "Eggshell", uniqueId: 280},
  {color: "Egyptian blue", uniqueId: 281},
  {color: "Eigengrau", uniqueId: 282},
  {color: "Electric blue", uniqueId: 283},
  {color: "Electric green", uniqueId: 284},
  {color: "Electric indigo", uniqueId: 285},
  {color: "Electric lime", uniqueId: 286},
  {color: "Electric purple", uniqueId: 287},
  {color: "Electric violet", uniqueId: 288},
  {color: "Emerald", uniqueId: 289},
  {color: "Eminence", uniqueId: 290},
  {color: "English green", uniqueId: 291},
  {color: "English lavender", uniqueId: 292},
  {color: "English red", uniqueId: 293},
  {color: "English vermillion", uniqueId: 294},
  {color: "English violet", uniqueId: 295},
  {color: "Erin", uniqueId: 296},
  {color: "Eton blue", uniqueId: 297},
  {color: "Fallow", uniqueId: 298},
  {color: "Falu red", uniqueId: 299},
  {color: "Fandango", uniqueId: 300},
  {color: "Fandango pink", uniqueId: 301},
  {color: "Fashion fuchsia", uniqueId: 302},
  {color: "Fawn", uniqueId: 303},
  {color: "Feldgrau", uniqueId: 304},
  {color: "Fern green", uniqueId: 305},
  {color: "Field drab", uniqueId: 306},
  {color: "Fiery rose", uniqueId: 307},
  {color: "Firebrick", uniqueId: 308},
  {color: "Fire engine red", uniqueId: 309},
  {color: "Fire opal", uniqueId: 310},
  {color: "Flame", uniqueId: 311},
  {color: "Flax", uniqueId: 312},
  {color: "Flirt", uniqueId: 313},
  {color: "Floral white", uniqueId: 314},
  {color: "Fluorescent blue", uniqueId: 315},
  {color: "Forest green (Crayola)", uniqueId: 316},
  {color: "Forest green (traditional)", uniqueId: 317},
  {color: "Forest green (web)", uniqueId: 318},
  {color: "French beige", uniqueId: 319},
  {color: "French bistre", uniqueId: 320},
  {color: "French blue", uniqueId: 321},
  {color: "French fuchsia", uniqueId: 322},
  {color: "French lilac", uniqueId: 323},
  {color: "French lime", uniqueId: 324},
  {color: "French mauve", uniqueId: 325},
  {color: "French pink", uniqueId: 326},
  {color: "French raspberry", uniqueId: 327},
  {color: "French rose", uniqueId: 328},
  {color: "French sky blue", uniqueId: 329},
  {color: "French violet", uniqueId: 330},
  {color: "Frostbite", uniqueId: 331},
  {color: "Fuchsia", uniqueId: 332},
  {color: "Fuchsia (Crayola)", uniqueId: 333},
  {color: "Fuchsia purple", uniqueId: 334},
  {color: "Fuchsia rose", uniqueId: 335},
  {color: "Fulvous", uniqueId: 336},
  {color: "Fuzzy Wuzzy", uniqueId: 337},
]